### ISSUE TITLE
SpellData Fields are Empty/wrong

### ISSUE THREAD

**Issue by happymaj00r** [Oasys-Zone/Oasys.SDK#1]
Most SpellData Fields like SpellName,ResourceCost,SpellRange are empty or return a wrong value 

Example: UnitManager.MyChampion.GetSpellBook().GetSpellClass(SpellSlot.Q).SpellData.SpellName returns blank

**Comment by ZeroLP** [comment]
This issue has been resolved in the 1.0.2.2 update.
