### ISSUE TITLE
Orbwalker OrbwalkingMode getting Stuck

### ISSUE THREAD

**Issue by happymaj00r** [Oasys-Zone/Oasys.SDK#2]
After pressing a Orbwalker Button (Space) The Orbwalker mode stays on 3/true and then the logic gets executed even when Space is not pressed
"if (Orbwalker.OrbwalkingMode == Oasys.Common.Logic.OrbwalkingMode.Combo)"

potential fix is to check if the button got released and then Set the Orbwalking Mode to 0 or any other number

**Comment by invulBox** [comment]
I've had this issue, its a problem with iskeypressed. But also tried getkeyasync still same issue. Only resolve that work for me is bool within time

**Comment by ZeroLP** [comment]
This issue is in intense monitoring state until viable solution is found in the future.

**Comment by SiXZZZ** [comment]
Fixed in next update
