### ISSUE TITLE
CastSpell casting to mouse 

### ISSUE THREAD

**Issue by happymaj00r** [Oasys-Zone/Oasys.SDK#3]
Sometimes when using  "SpellCastProvider.CastSpell(CastSlot.Q, Enemy.Position);"  the spell will be casted to mouse position instead of the Enemy.Position even when the Enemy.Position is valid

i am guessing the Mouse returns to quickly to its normal position and thats why this is happening

**Comment by ZeroLP** [comment]
This issue has been (potentially) fixed in the latest patch. If any further issues, please reopen the thread.
