### ISSUE TITLE
Invalid properties

### ISSUE THREAD

**Issue by invulBox** [Oasys-Zone/Oasys.SDK#5]
Unit.GetAttackDelay | Doesn't update until loader restarts.
SpellActiveEntry: CastEndTime,CastStartTime, and SpellCurrentPosition aren't returning anything (valid).
GameEvents.OnProcessSpell | Doesn't trigger.

These are the only unavoidable problems I could see. Can't detect projectiles pos without one of those spellentryies (accurately).

**Comment by ZeroLP** [comment]
This should now be fixed in the latest core update.
